from pathlib import Path

__version__: str

def to_json(xml: str) -> str: ...
def to_flatten_json(xml: str, separator: str = ".") -> str: ...
def to_dict(xml: str) -> dict: ...
def to_flatten_dict(xml: str, separator: str = ".") -> dict: ...
def to_csv(xml: str, include_attrs: bool = True) -> str: ...
def to_parquet(xml: str, path: str | Path, include_attrs: bool = True) -> None: ...
