from os import PathLike
from pathlib import Path

__version__: str

XmlInput = str | Path | PathLike[str]

def to_json(xml: XmlInput) -> str: ...
def to_flatten_json(xml: XmlInput, separator: str = ".") -> str: ...
def to_dict(xml: XmlInput) -> dict: ...
def to_flatten_dict(xml: XmlInput, separator: str = ".") -> dict: ...
def to_csv(xml: XmlInput, include_attrs: bool = True) -> str: ...
def to_parquet(xml: XmlInput, path: str | Path, include_attrs: bool = True) -> None: ...
